### ISSUE TITLE
What does this error mean

### ISSUE THREAD

**Issue by ooochen-30** [IGLICT/DeepFaceVideoEditing#4]
i try to run the command(python run_editing.py) but it always can not generate the mask_warp picture successfully. 

-----------------
warp mask: 0/1
Traceback (most recent call last):
  File "run_editing.py", line 188, in <module>
    predictions = make_mask_animation(source_image, mask_image, driving_video, generator, kp_detector, relative=False, adapt_movement_scale=False)
  File "/home/xdy/code/DeepFaceVideoEditing-main/warp_mask.py", line 64, in make_mask_animation
    mask = jt.array(mask_image[np.newaxis].astype(np.float32)).permute(0, 3, 1, 2)
  File "/home/xdy/anaconda3/envs/jittor/lib/python3.8/site-packages/jittor/__init__.py", line 569, in transpose
    return origin_transpose(x, dim)
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.ops.transpose)).

Types of your inputs are:
 self	= module,
 args	= (Var, tuple, ),

The function declarations are:
 VarHolder* transpose(VarHolder* x,  NanoVector axes=NanoVector())

Failed reason:[f 0202 14:39:38.463771 60 transpose_op.cc:62] Check failed axes.size()(4) == xdim(3)

**Comment by ty625911724** [comment]
Thanks for your interests! We have updated the released code and you can try again with the example scripts.
